---
- name: Наливаю юнит файл haproxy
  ansible.builtin.template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
  notify:
    - Перезапускаю haproxy.service

- name: Настраиваю haproxy.service
  ansible.builtin.systemd:
    name: haproxy.service
    state: started
    enabled: true
