name: AURO PR

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Auto Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: main
